name: Build and Push Multi-Arch Docker Images

# 触发条件：路径触发（src路径下面的代码有变动或Dockerfile有变动时触发自动构建）或者创建以 v 开头的 tag 时触发
on:
  push:
    paths:
      - '*.py'
      - 'Dockerfile'
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  build-and-push-docker-image:
    name: Build and Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      # 用于构建多平台 Docker 镜像

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      # 用于构建多平台 Docker 镜像

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      # secrets.DOCKER_USERNAME 和 secrets.DOCKER_PASSWORD 应在 GitHub repository secrets 中设置

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}
        tags: |
          type=ref,event=branch
          type=sha,enable=true
          type=semver,pattern={{version}}
          latest

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Image digest
      run: echo "Image digest - ${{ steps.docker_build.outputs.digest }}"
